FHIR Gateway Enhancements
onaio/fhir-gateway-extension pull request #92
Opened 2024-10-25 07:13 UTC by ndegwamartin

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

**In this PR**
- Fix REL sync strategy Caching bug
- Refactor to support returning all paginated results
- Refactor REL upstream fetch to single request
- Pagination count bumped to 200
- Release version 2.1.2

**Engineer Checklist**

- [ ] I have written **Unit tests** for any new feature(s) and edge cases for
      bug fixes
- [ ] I have added documentation for any new feature(s) and configuration
      option(s) on the `README.md`
- [ ] I have run `mvn spotless:check` to check my code follows the project's
      style guide
- [ ] I have run `mvn clean test jacoco:report` to confirm the coverage report
      was generated at `plugins/target/site/jacoco/index.html`
- [ ] I ran `mvn clean package` right before creating this pull request.

2024-11-11 07:39 UTC, dubdabasoduba requested changes

2024-11-11 07:39 UTC, dubdabasoduba commented on exec/pom.xml
> +    <version>2.1.2.0</version>
Update to the correct version, we already have `2.1.2.3` deployed.

2024-11-11 07:39 UTC, dubdabasoduba commented on exec/pom.xml
> +      <version>2.1.2.0</version>
Same as above

2024-11-11 07:39 UTC, dubdabasoduba commented on plugins/pom.xml
> +    <version>2.1.2.0</version>
Same as above

2024-11-11 07:39 UTC, dubdabasoduba commented on pom.xml
> +  <version>2.1.2.0</version>
Same as above

2024-11-15 09:45 UTC, ndegwamartin commented on plugins/src/main/java/org/smartregister/fhir/gateway/plugins/PermissionAccessChecker.java
> +                        throw new IllegalStateException("No _syncLocation query param specified");
@dubdabasoduba how should the Gateway respond for requests that are using REL but do not have _syncLocation specified?

2024-11-15 09:50 UTC, dubdabasoduba commented on plugins/src/main/java/org/smartregister/fhir/gateway/plugins/PermissionAccessChecker.java
> +                        throw new IllegalStateException("No _syncLocation query param specified");
It should return an error saying that the sync locations are not set.  However, We should ensure the requests made from the composition resources don't throw that error. Those requests are not affected by the sync strategies.

2024-11-15 11:13 UTC, ndegwamartin commented on plugins/src/main/java/org/smartregister/fhir/gateway/plugins/PermissionAccessChecker.java
> +                        throw new IllegalStateException("No _syncLocation query param specified");
I think those coming from composition should be ignored on the Allowed Queries or the Ignore Sync filter configuration file.

2025-01-29 12:36 UTC, closed without merging